language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: m7AJ4T6kU1OXj8BjLHYVbXkcrtaqlUvukMzen1BP4cTvYsSQ49S0eernVJsIFVf+2mOjeb+OTlfEg0weXTdAnTSO2w5JEaH8wat79tSb2byrur2riUnJ0dMF8lgTPlB5DDd9uWUSLpG5SdyGHFc0/yaKKVCNu3wiyJ5vsXTvPweOcvOpM9OFl8WP6rjvHzux8v/TsvF7K46RkxXBKzMLDCBxX8Ijlx5EMWacoXQl22aLcn2fWo2A71WpvkGdBjn5p1imUNAPOEKqmo3uy9yTn5UzIEKSCFWT1nCauNNEfOAYRPfwdLdWjC8RtqKIr/lKmxAm7QoEkP9oZMzemGpIIP8WSuOHq/jHZwNz6PF8fikKZcFlYBxXk7JDWu/GJfRZsBcd6CYcHyY4zJe/kLvVVW7AqmCIwjkgb5Qvxt5vp2kUASAtGGSiCfZyMhtLQ2xQ1qjGYSytMvTvf3TKXLbLJoorHszXxqhHMH/uo5gYcm2WSfqrVJqFdjQUELV24CcYzjYq/2sA7+rYXJRn2N1r91Yba6YyB5N3JOfqeN52vpTxT/vppaoo/KqZP2vVujlIjaKKr/KZ0n2g24pi72Vz2PSeOz9vSuuff5Yq9L+/CJJtIbqsZP7pI9TMDuFIks4vKGdS1/b8j154B9QZVA5OCajUFvJwnI7whFToTe2QgqQ=
  app: duncan-noteful-app-v3a
  on:
    repo: thinkful-ei19/duncan-noteful-app-v3a
